StartupEvents.registry("block", (event) => {
	function addBlock(name) {
		return event.create(`${Cmi.MODID}:${name}`)
	}
	// 火箭框架
	addBlock("rocket_pattern")
		.soundType(SoundType.WOOD)
		.model(Cmi.loadResource("block/rocket/pattern/rocket_pattern"))
		.hardness(5)
		.resistance(5)
		.item((item) => {
			item.maxStackSize(1)
		})
		.notSolid()
		.defaultTranslucent()
		.requiresTool(false)
		.box(0, 0, 0, 16, 45, 16, true)
		.tagBlock(CmiToolType.PICKAXE.tag())
		.tagBlock(CmiToolType.AXE.tag())
		.tagBlock(CmiMiningLevel.WOODEN.tag())
		.tagBlock(CmiGlobal.WRENCH_PICKUP)

	// 火箭框架1
	addBlock("tier_1_rocket_frame")
		.soundType(SoundType.NETHERITE_BLOCK)
		.model(Cmi.loadResource("block/rocket/tier1/tier1"))
		.hardness(5)
		.resistance(5)
		.item((item) => {
			item.maxStackSize(1)
		})
		.notSolid()
		.defaultTranslucent()
		.requiresTool(false)
		.box(0, 0, 0, 16, 45, 16, true)
		.tagBlock(CmiToolType.PICKAXE.tag())
		.tagBlock(CmiMiningLevel.IRON.tag())
		.tagBlock(CmiGlobal.WRENCH_PICKUP)

	// 火箭框架2
	addBlock("tier_2_rocket_frame")
		.soundType(SoundType.NETHERITE_BLOCK)
		.model(Cmi.loadResource("block/rocket/tier2/tier2"))
		.hardness(5)
		.resistance(5)
		.item((item) => {
			item.maxStackSize(1)
		})
		.notSolid()
		.defaultTranslucent()
		.requiresTool(false)
		.box(0, 0, 0, 16, 45, 16, true)
		.tagBlock(CmiToolType.PICKAXE.tag())
		.tagBlock(CmiMiningLevel.IRON.tag())
		.tagBlock(CmiGlobal.WRENCH_PICKUP)

	// 火箭框架3
	addBlock("tier_3_rocket_frame")
		.soundType(SoundType.NETHERITE_BLOCK)
		.model(Cmi.loadResource("block/rocket/tier3/tier3"))
		.hardness(5)
		.resistance(5)
		.item((item) => {
			item.maxStackSize(1)
		})
		.notSolid()
		.defaultTranslucent()
		.requiresTool(false)
		.box(0, 0, 0, 16, 45, 16, true)
		.tagBlock(CmiToolType.PICKAXE.tag())
		.tagBlock(CmiMiningLevel.IRON.tag())
		.tagBlock(CmiGlobal.WRENCH_PICKUP)

	// 火箭框架4
	addBlock("tier_4_rocket_frame")
		.soundType(SoundType.NETHERITE_BLOCK)
		.model(Cmi.loadResource("block/rocket/tier4/tier4"))
		.hardness(5)
		.resistance(5)
		.item((item) => {
			item.maxStackSize(1)
		})
		.notSolid()
		.defaultTranslucent()
		.requiresTool(false)
		.box(0, 0, 0, 16, 45, 16, true)
		.tagBlock(CmiToolType.PICKAXE.tag())
		.tagBlock(CmiMiningLevel.IRON.tag())
		.tagBlock(CmiGlobal.WRENCH_PICKUP)
})